# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title-bold: cowboy.cloud
title-normal: Just a cowboy in a cloud
email: hello@cowboy.cloud
description: |
  Thoughts and musings on technology from <br />
  the perspective of a cattle rancher.
baseurl: ""
url: "https://cowboy.cloud"
author: 
street_address: 1234 Somewhere Road
city: Bisbee
state: AZ
zip_code: 55555
country: United States of America
phone: (602) 555-5555

# Plugins
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jemoji

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages" 
tiles-count: 6

# Social settings
500px_url: 
facebook_url: 
github_url: 
# gitlab_url: https://gitlab.com/u/andrewbanchich
# googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
instagram_url: https://instagram.com
# linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url: 
slack_url: 
# twitter_url: https://twitter.com/CowboyCloud

# Build settings
markdown: kramdown

# Plugin: jekyll-seo-tag
twitter:
  username: CowboyCloud
# Add one or more of the following
facebook:
  app_id: 
  publisher: 
  admins: 
  logo:
google_site_verification: 
